### ISSUE TITLE
JSON decode error when parsing Twitter posts

### ISSUE THREAD

**Issue by Dinth** [cquest/tootbot#16]
Im getting this error when im trying to run the script:
```
dinth1906
---------------------------
Traceback (most recent call last):
  File "/home/dinth/tootbot/tootbot.py", line 158, in <module>
    d = json.load(open('tweets.json','r'))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by produnis** [comment]
Me too, same error....

**Comment by loxK** [comment]
Guys, install the `jq` utility : 

`apt install jq`

**Comment by produnis** [comment]
thanks a lot loxK, installing `jq` solved the problem for me...

**Comment by Arnaud-Albrecht** [comment]
I did install it, but to no avail, i'm on windows though.
